"""Analytics visualization agent node for chart generation."""

import time
from typing import Any

from app.agents.state import NexusState
from app.services.chart_service import generate_dynamic_chart_base64


async def analytics_node(state: NexusState) -> dict[str, Any]:
    """
    Analytics node: evaluates if database query results can be visualized,
    generates a custom Plotly chart dynamically using python code execution,
    and returns a base64 PNG string.
    """
    start_time = time.time()
    
    # 1. Skip if chart already generated by Python CSV Agent
    if state.get("chart_base64"):
        trace = {
            "node_name": "AnalyticsAgent",
            "status": "success",
            "latency_ms": 0,
            "tokens_used": 0,
            "metadata": {"reason": "Chart already generated by RAG CSV Agent."}
        }
        return {
            "agent_trace": [trace]
        }
        
    # 2. Skip if SQL results are empty or not present
    results = state.get("sql_results")
    if not results or "error" in results[0] if results else False:
        trace = {
            "node_name": "AnalyticsAgent",
            "status": "skipped",
            "latency_ms": 0,
            "tokens_used": 0,
            "metadata": {"reason": "No SQL results available or error occurred."}
        }
        return {
            "chart_base64": None,
            "agent_trace": [trace]
        }
        
    query = state["original_query"]
    
    chart_base64 = None
    status = "success"
    
    try:
        # 2. Generate Plotly chart image base64 dynamically via LLM code execution
        chart_base64 = await generate_dynamic_chart_base64(query, results)
        if not chart_base64:
            status = "skipped"  # Not suitable for chart or skipped
            
    except Exception as e:
        status = "failed"
        print(f"Analytics node execution error: {e}")
        
    latency = int((time.time() - start_time) * 1000)
    
    trace = {
        "node_name": "AnalyticsAgent",
        "status": status,
        "latency_ms": latency,
        "tokens_used": 0,
        "metadata": {
            "chart_generated": chart_base64 is not None
        }
    }
    
    return {
        "chart_base64": chart_base64,
        "agent_trace": [trace]
    }
